name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: List build output (Linux)
        run: ls -lR build/

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: metamod-linux
          path: build/**/*.so

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup MSBuild tools
        uses: microsoft/setup-msbuild@v1.1

      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: cmake --build build --config Release

      - name: List build output (Windows)
        run: dir build\Release\

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: metamod-windows
          path: build/Release/*.dll
